"""add user url visit count

Revision ID: 0076e52381bf
Revises: b1b3b17f3914
Create Date: 2025-08-30 22:17:04.905448

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0076e52381bf"
down_revision: str | Sequence[str] | None = "b1b3b17f3914"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("url_visit_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "url_visit_count")
    # ### end Alembic commands ###
