"""create anonymous message

Revision ID: b1b3b17f3914
Revises: 63de8dca9b30
Create Date: 2025-08-30 21:02:25.354239

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b1b3b17f3914"
down_revision: str | Sequence[str] | None = "63de8dca9b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anonymous_message",
        sa.Column("to_user_id", sa.Integer(), nullable=False),
        sa.Column("to_message_id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("from_message_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("to_user_id", "to_message_id", "from_user_id", "from_message_id"),
    )
    op.create_index(
        op.f("ix_anonymous_message_from_message_id"), "anonymous_message", ["from_message_id"], unique=False
    )
    op.create_index(op.f("ix_anonymous_message_from_user_id"), "anonymous_message", ["from_user_id"], unique=False)
    op.create_index(op.f("ix_anonymous_message_to_message_id"), "anonymous_message", ["to_message_id"], unique=False)
    op.create_index(op.f("ix_anonymous_message_to_user_id"), "anonymous_message", ["to_user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_anonymous_message_to_user_id"), table_name="anonymous_message")
    op.drop_index(op.f("ix_anonymous_message_to_message_id"), table_name="anonymous_message")
    op.drop_index(op.f("ix_anonymous_message_from_user_id"), table_name="anonymous_message")
    op.drop_index(op.f("ix_anonymous_message_from_message_id"), table_name="anonymous_message")
    op.drop_table("anonymous_message")
    # ### end Alembic commands ###
