"""create user

Revision ID: 63de8dca9b30
Revises:
Create Date: 2025-08-30 14:46:49.583088

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "63de8dca9b30"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_url"), "user", ["url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_url"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
